### PR TITLE
feat(io): compare actual size in CheckIsFileSizeSame

### PR DESCRIPTION
**Pull request by c3y1huang**
#### Which issue(s) this PR fixes:

Issue longhorn/longhorn#4105

#### What this PR does / why we need it:

https://github.com/longhorn/longhorn-engine/pull/1003#discussion_r1660225197

### CODE REVIEW

**Comment by c3y1huang** [comment]
I was expecting [this TestCopyFile test case](https://github.com/longhorn/go-common-libs/blob/main/io/file_test.go#L301) to fail after this PR due to [this](https://github.com/longhorn/longhorn-engine/pull/1003#discussion_r1660224390) and [this](https://github.com/longhorn/longhorn-engine/pull/1003#discussion_r1660225197), but it didn't. I am not sure why. @derekbit any idea?

**Comment by c3y1huang** [comment]
I cannot see how [copySparseData](https://github.com/longhorn/sparse-tools/blob/ed49dd3f93eb42590d1b57686572ee739106c099/sparse/test/sfold_test.go#L153) in the unit test handles sparse data differently from io.Copy.

**Comment by derekbit** [comment]
> I was expecting [this TestCopyFile test case](https://github.com/longhorn/go-common-libs/blob/main/io/file_test.go#L301) to fail after this PR due to [this](https://github.com/longhorn/longhorn-engine/pull/1003#discussion_r1660224390) and [this](https://github.com/longhorn/longhorn-engine/pull/1003#discussion_r1660225197), but it didn't. I am not sure why. @derekbit any idea?

IIUC, the test case creates a temp file with a string "content" and truncate the file to 20 bytes, so the file content is 
`'c' 'o' 'n' 't' 'e' 'n' 't' '\x00' .... '\x00'`. Then, copy the content to the destination file.
Can you elaborate more on that why you think the test case should fail?

**Review by derekbit — DISMISSED** [review]
LGTM

**Comment by c3y1huang** [comment]
> IIUC, the test case creates a temp file with a string "content" and truncate the file to 20 bytes, so the file content is
> `'c' 'o' 'n' 't' 'e' 'n' 't' '\x00' .... '\x00'`. Then, copy the content to the destination file.
> Can you elaborate more on that why you think the test case should fail?

I’m a bit confused. I was expecting it to fail because we are now comparing actual sizes, and `io.Copy` doesn't support sparse file copy?

**Comment by derekbit** [comment]
> > IIUC, the test case creates a temp file with a string "content" and truncate the file to 20 bytes, so the file content is
> > `'c' 'o' 'n' 't' 'e' 'n' 't' '\x00' .... '\x00'`. Then, copy the content to the destination file.
> > Can you elaborate more on that why you think the test case should fail?
> 
> I’m a bit confused. I was expecting it to fail because we are now comparing actual sizes, and `io.Copy` doesn't support sparse file copy?
> 
> [longhorn/longhorn-engine#1003 (comment)](https://github.com/longhorn/longhorn-engine/pull/1003#discussion_r1660224390)

I see.
The size of the sparse file is only 20 bytes. A file is composed of blocks, with each block typically being 512 bytes or 4096 bytes. Although the file's apparent size is 20 bytes, it actually occupies 8 blocks on the disk. This results in a total disk usage of 8 blocks x 512 bytes (disk sector size). Therefore, the file is not sparse. 
``` 
# echo content > test
# truncate --size 20 test
# stat test
  File: test
  Size: 20        	Blocks: 8          IO Block: 4096   regular file
Device: fd00h/64768d	Inode: 3407888     Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2024-07-01 15:09:03.514369106 +0000
Modify: 2024-07-01 15:10:02.550371344 +0000
Change: 2024-07-01 15:10:02.550371344 +0000
 Birth: 2024-07-01 15:09:03.514369106 +0000
```

You can try 
- Write string "content"
- Truncate the file to 4097 bytes
Then, the file should be sparse.
```
# echo content > test
# truncate --size 4097 test
# stat test
  File: test
  Size: 4097      	Blocks: 8          IO Block: 4096   regular file
Device: fd00h/64768d	Inode: 3407888     Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2024-07-01 15:09:03.514369106 +0000
Modify: 2024-07-01 15:16:08.726461833 +0000
Change: 2024-07-01 15:16:08.726461833 +0000
 Birth: 2024-07-01 15:09:03.514369106 +0000
```

**Comment by c3y1huang** [comment]
> I see. The size of the sparse file is only 20 bytes. A file is composed of blocks, with each block typically being 512 bytes or 4096 bytes. Although the file's apparent size is 20 bytes, it actually occupies 8 blocks on the disk. This results in a total disk usage of 8 blocks x 512 bytes (disk block size). Therefore, the file is not sparse.
> 
> Note: `Blocks` is the number of blocks allocated on the disk, and the disk block size is 512 bytes. `IO Block` is the block size of the filesystem.
> 
> ```
> # echo content > test
> # truncate --size 20 test
> # stat test
>   File: test
>   Size: 20        	Blocks: 8          IO Block: 4096   regular file
> Device: fd00h/64768d	Inode: 3407888     Links: 1
> Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
> Access: 2024-07-01 15:09:03.514369106 +0000
> Modify: 2024-07-01 15:10:02.550371344 +0000
> Change: 2024-07-01 15:10:02.550371344 +0000
>  Birth: 2024-07-01 15:09:03.514369106 +0000
> ```
> 
> You can try
> 
> * Write string "content"
> * Truncate the file to 4097 bytes
>   Then, the file should be sparse. You can see the actual size is 8 blocks x 512 bytes (disk block size), but the apparent size is 4097.
> 
> ```
> # echo content > test
> # truncate --size 4097 test
> # stat test
>   File: test
>   Size: 4097      	Blocks: 8          IO Block: 4096   regular file
> Device: fd00h/64768d	Inode: 3407888     Links: 1
> Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
> Access: 2024-07-01 15:09:03.514369106 +0000
> Modify: 2024-07-01 15:16:08.726461833 +0000
> Change: 2024-07-01 15:16:08.726461833 +0000
>  Birth: 2024-07-01 15:09:03.514369106 +0000
> ```

Thank you for the explanation, it's clear to me now.

**Review by derekbit — APPROVED** [review]
LGTM

**Pull request merged**
