### PR TITLE
chore(vendor): pin k8s libs to 0.28.5

### PR DESCRIPTION
**Pull request by derekbit**
#### Which issue(s) this PR fixes:

Issue #

#### What this PR does / why we need it:

- v1.6.x is using k8s libs 0.28.5
- v1.6.x and v1.7.x is using go 1.22

### CODE REVIEW

**Review by c3y1huang — COMMENTED** [review]
Does this imply that the `go-common-lib` must always align with the version used in the minimum active Longhorn supported release? If so, could this potentially become a blocker for updating Kubernetes dependencies?

**Comment by c3y1huang** [comment]
> I am not sure about this change. Does this imply that the `go-common-lib` must always align with the version used in the minimum actively supported Longhorn version? If so, could this potentially become a blocker for updating Kubernetes or other dependencies?

After talking to @derekbit , we've considered two potential approaches:
1. **Align with the Longhorn Manager dep versions**: Use the dependency versions specified in `longhorn-manager` of the minimum actively supported longhorn release.
1. **Versioned branches from `go-common-lib`:** Maintain separate versioned branches for `go-common-lib`, this can ensure compatibility across different Longhorn component versions.

We will proceed with the first approach, and see how this fits.

Related: https://github.com/longhorn/longhorn-manager/pull/2908

**Review by c3y1huang — APPROVED** [review]

**Comment by innobead** [comment]
> I am not sure about this change. Does this imply that the `go-common-lib` must always align with the version used in the minimum actively supported Longhorn version? If so, could this potentially become a blocker for updating Kubernetes or other dependencies?

There should not be an issue unless there is a compatibility problem between versions, as the higher version will be chosen. For example, if a higher k8s-api version is used in longhorn-manager than in go-common-lib, the higher version will take precedence.

**Comment by innobead** [comment]
> 2\. **Versioned branches from `go-common-lib`:** Maintain separate versioned branches for `go-common-lib`, this can ensure compatibility across different Longhorn component versions.

This should be prevented if possible. This might cause our maintenance efforts. This is why we introduce a shared library like we did for other longhorn go libraries. 

We had some pains before when maintaining branches shared libraries.

**Comment by derekbit** [comment]
> We had some pains before when maintaining branched shared libraries like backupstore 1.3/1.4?

Yes, it is a dilemma...
If we start branching go-common-libs, then we need to branch go-iscsi-helper, backupstore, longhorn-manager.....

**Comment by innobead** [comment]
I added this lib update policy for shared libs in https://github.com/longhorn/longhorn/wiki/Version-Update-Policy#library-depednecy-update-in-shared-libraries for future reference. 

cc @longhorn/dev

**Pull request merged**
